trigger:
  branches:
    include:
      - main  # Cambia "main" si tu rama principal tiene otro nombre

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Cambia la versión de Node.js según lo necesites
  displayName: 'Instalar Node.js'

- script: npm install
  displayName: 'Instalar dependencias'

- script: npm run test
  displayName: 'Ejecutar pruebas Selenium'
